# Generated by Django 4.1.2 on 2022-11-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'entries'},
        ),
        migrations.RemoveField(
            model_name='topping',
            name='name',
        ),
        migrations.AddField(
            model_name='topping',
            name='topping_list',
            field=models.TextField(default=1000),
            preserve_default=False,
        ),
    ]
